
import { Poppins } from 'next/font/google'

const pp = Poppins({ subsets: ['latin'] , weight: ['400'] })
import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Karigar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pp.className}>{children}</body>
    </html>
  )
}
